/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for HelloWorldRestApi
 */
@Disabled
public class HelloWorldRestApiTest {

    private final HelloWorldRestApi api = new HelloWorldRestApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void helloWorldTest()  {
        String response = api.helloWorld();

        // TODO: test validations
    }
    
}