/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for UserServicesApi
 */
@Disabled
public class UserServicesApiTest {

    private final UserServicesApi api = new UserServicesApi();


    /**
     * Delete a user
     *
     *
     */
    @Test
    public void deleteUserTest() {
        Integer id = null;
        Boolean response = api.deleteUser(id);

        // TODO: test validations
    }

    /**
     * Returns all users
     *
     *
     */
    @Test
    public void getAllUsersTest() {
        User response = api.getAllUsers();

        // TODO: test validations
    }

    /**
     * Register a new user
     *
     *
     */
    @Test
    public void registerTest() {
        String name = null;
        User response = api.register(name);

        // TODO: test validations
    }

    /**
     * Update a user&#39;s name
     *
     *
     */
    @Test
    public void updateUserTest() {
        Integer id = null;
        String newName = null;
        User response = api.updateUser(id, newName);

        // TODO: test validations
    }

}