spring:
  profiles:
    active: test
sample:
  string-array-sample:
    - aaa
    - bbb
    - ccc
  boolean-sample: false
  string-sample: "config string"
  integer-sample: 10
  enum-sample: en2
  collection-sample:
    - test1
    - test2
    - test3
  map-sample:
    test1: test1value
    test2: test2value
  map-object-sample:
    item1:
      config-map1: abc
      config-map2: 1000
    item2:
      config-map1: abc
      config-map2: 1001

  config-sample-nested:
    nested-config1: nestedConfig
  deep-level1:
    deep-level2:
      list1:
        - id: "1"
          prop1: "1234"
          prop2: "1234"
        - id: "2"
          prop1: "1234"
          prop2: "1234"
      list2:
        - id: "1"
          prop1: "1234"
          prop2: "1234"
        - id: "2"
          prop1: "1234"
          prop2: "1234"

---
spring:
  config:
    activate:
      on-profile: test

sample:
  string-sample: "Test profile"



