spring.boot.admin.client.url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always



