spring:
  profiles:
    active: test

sample:
  boolean-sample: false
  string-sample: "config string"
  integer-sample: 10
  enum-sample: en2
  collection-sample:
    - test1
    - test2
    - test3
  map-sample:
    test1: test1value
    test2: test2value

  config-sample-nested:
    nested-config1: nestedConfig
logging:
  level:
    root: info
    sun:
      rmi: error
    javax:
      management: error

server:
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      cookie:
        partitioned: true
---
spring:
  config:
    activate:
      on-profile: test

sample:
  string-sample: "Test profile"



