server:
  port: 8086
spring:
  application:
    name: simple-boot-supervisor
  task:
    execution:
      thread-name-prefix: "process-pool-"
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 25

process:
  name: test
  command: "java"
  working-directory: "/Users/alex.mondshain/IdeaProjects/spring-boot-playground/spring-boot-supervisor/work"
  stdout-logfile: ${process.working-directory}/stdout.log
  stderr-logfile: ${process.working-directory}/error.log
  args:
    - "-version"

logging:
  level:
    root: debug
    sun:
      rmi: info
    javax:
      management:
        remote:
          rmi: info





