spring:
  application:
    name: spring-boot-ai-samples
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  
  # AI Configuration (OpenAI)
  ai:
    openai:
      chat:
        options:
          model: grok-4
      base-url: https://api.x.ai/
#      base-url: https://api.groq.com/openai

# Server configuration
server:
  port: 8080

# Logging
logging:
  level:
    org.alexmond.ai: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
