spring:
  application:
    name: spring-boot-auth-roles
server:
    port: 8080
users:
  admin-users:
    - user: user
      password: password
      role: USER
    - user: user2
      password: password2
      role: ADMIN
