server:
  port: 8090

spring:
  application:
    name: spring-boot-admin-server
  boot.admin.client.url: http://localhost:8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always

info:
  tags:
    environment: OPS

