spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
sample:
  config1: "common config"

management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    tags:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always
    httpexchanges:
      access: unrestricted
      cache:
        time-to-live: 100000

logging:
  file:
    name: logs/server.log