sample:
  config1: "common config"

info:
  tags:
    environment: QA
    location: NY

---
spring:
  config:
    activate:
      on-profile: srv1
server:
  port: 8081
sample:
  config2: "service srv1 config"

---
spring:
  config:
    activate:
      on-profile: srv2
server:
  port: 8082
sample:
  config2: "service srv1 config"