name: Java CI with Maven
on: [push, manual]
push:
  branches: [main]
jobs:
  build:
    image: maven:3.9-eclipse-temurin-17
    cache:
      key: m2-spring-boot-playground
      paths: [.m2/repository]
    steps:
      - name: Checkout
        run: git clone --depth 1 https://github.com/alexmond/spring-boot-playground.git .
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.repo.local=.m2/repository
